### ISSUE TITLE
Does not work with capitalized file extension

### ISSUE THREAD

**Issue by Stfb** [danm/image-hash#1]
Hi !
I was testing on jpeg files with a upper case extension like 'JPG'.
Does not work saying "File extension no reconised".
Might be good to change that in image-hash.js line 24 ..

Thanks !

**Comment by danm** [comment]
I haven't tested but looks like @mparpaillon may have fixed the case sensitivity issue

**Comment by mparpaillon** [comment]
@danm Yup. Should work fine
