### ISSUE TITLE
python image hash

### ISSUE THREAD

**Issue by adriangoris** [danm/image-hash#11]
Hashes do not seem to generate the same hex string as in python's [image-hash ](https://pypi.org/project/ImageHash/) implementation of image hash. 
You can read more about it from this article: [Evaluating Perceptual Image Hashes at OkCupid](https://tech.okcupid.com/evaluating-perceptual-image-hashes-okcupid/)

Is there a different perceptual hash algorithm being implemented?

**js image-hash output**: _95703623_mediaitem95703620.JPG
`fc08de38c3f803f001fe007f103f3f0ebf7f337da00180310001003f03fffdfd`

**python image-hash outputs**:  _95703623_mediaitem95703620.JPG
**md5 Hash:**
`3953e5ca3e33c46594cd738d870376fe`

**imagehash.average_hash(img, 16):**
`ffffffffcfffc7ff01ff007ffc7f3f7f0f7e000000000001000380ffffffffff`
**imagehash.phash(img, 16):**
`bee69414cb916acbc42e336170bf957e8a43ccd9f5313a423fa4613d8ec0e586`
**imagehash.phash_simple(img, 16):**
`f949f969ed69ed69eda5eda5b5a9b5a93f833f013c013c033cc33cc730e301e7`
**imagehash.dhash(img, 16):**
`001130721e6386067fe001c0e0f0fe5c5e5847506b3b356735e73ff87e0d81c1`
**imagehash.dhash_vertical(img, 16):**
`3ef2804d038f0c0c0020ff977f86017c0000a080c0010e73ffdeffff7f80e0f1`
**imagehash.whash(img, 16):**
`ffffffffc7ff43ff00fe007e003e070e015c000000000001000180ffffffffff`

**Comment by danm** [comment]
its a different algorithm. there is a paper written about the type that is used here https://pdfs.semanticscholar.org/b59b/14d3a0d7047a63cbbcfc25582fb915f60664.pdf
