### ISSUE TITLE
Support for Node.js < 10.x.x  

### ISSUE THREAD

**Issue by turakvlad** [danm/image-hash#15]
Hello, guys!

At first, I'd like to say thank you for this library!

Have you thought about adding support for older Node.js versions? This library support 10.x.x and above because of [this line of code](https://github.com/danm/image-hash/blob/master/src/imageHash.ts#L67) only.

To be honest, I spent 1-2 hours to understand where the problem is. Everything worked perfect on my local machine but failed in the production environment. On my local machine I have Node.js 10.16.3 and on the production - 8.16.1. And that was the issue.

`URL` class is available globally only from 10.x.x - https://nodejs.org/docs/latest-v10.x/api/globals.html. It is not available for 8.x.x and lower - https://nodejs.org/docs/latest-v8.x/api/globals.html.

I am not sure but it looks like we can older versions if we require Node.js `url` module by `import URL from 'url'` at the top of https://github.com/danm/image-hash/blob/master/src/imageHash.ts. Also, it should not be a braking change.

If you don't want to do that, could you please specify that library works with Node.js 10.x.x and above only? It would be great to have this information in the README file. Also, you can use `package.json` property `engine` to specify supported Node.js versions - https://docs.npmjs.com/files/package.json#engines.

I really spent about 1-2 hours to understand what's wrong. Just want to help other folks who may face this issue.

**Comment by danm** [comment]
hi @turakvlad, sorry for the delay. Good point about `URL` only becoming global in > v10.

@dills122 very kindly fixed this by import `URL`. I've also compiled down to ES2015 rather than ES2018 which might help too.

give `npm i -S image-hash@3.5.0` a shot and let me know if it works for you.

**Comment by danm** [comment]
Closed due to inactivity
