### ISSUE TITLE
Error: Mime type not found at checkFileType

### ISSUE THREAD

**Issue by heyFahad** [danm/image-hash#22]
How can I override this mime type check while generating a hash? My script works fine in macOS, but when I try to execute the same script inside a Ubuntu based docker container, I get this `Mime type not found` error.
Basically, I'm first downloading the corresponding image from my server and then pass its path to imageHash function. I'm testing the script with same image URL on both macOS and Ubuntu container. MacOS does give me an output saying `No file extension found, attempting mime typing.` but then it works fine.
So my questing is, how can override this mime type checking? Can I??

**Comment by danm** [comment]
No you can't override it, annoyingly. If this is still a feature you need, create a new issue requesting a feature to skip file check, as long as the file extension is at the end of the file name.
