### ISSUE TITLE
Issue with New Input Types Exports

### ISSUE THREAD

**Issue by dills122** [danm/image-hash#28]
## Issue
After updating the package to latest with that patch [PR](https://github.com/danm/image-hash/pull/27) I'm still noticing that error. After some further investigation it looks like the type definition file `imageHash.d.ts` didn't get updated with exports in the patched version.

[PR](https://github.com/dills122/mtg-processor/pull/10)
[Build Error](https://travis-ci.org/github/dills122/mtg-processor/builds/714630855)

## Recreate Issue

Command to recreate issue:
```bash
mkdir test-image-hash && cd ./test-image-hash && npm init --yes && npm i image-hash@latest && cat node_modules/image-hash/lib/imageHash.d.ts | grep interface
```

Actual Output:
```
interface UrlRequestObject {
interface BufferObject {
```

Expected Output:
```
export interface UrlRequestObject {
export interface BufferObject {
```

## Possible Fix for Issue

If you run a clean build it looks like it will fix the issue.

```bash

rm -rf lib/ && npm run build && cat lib/imageHash.d.ts | grep interface
# Either or
npx tsc --build --clean  && npm run build && cat lib/imageHash.d.ts | grep interface
```

Sorry for the trouble with this little patch issue.

**Comment by danm** [comment]
this is now fixed as of version `5.3.0`
