### ISSUE TITLE
Getting extraneous console output "No file extension found, attempting mime typing."

### ISSUE THREAD

**Issue by alexdpoon** [danm/image-hash#29]
I have a Buffer called imageBuffer that I know is an image/jpeg, so I make the call to image-hash like this:

`const myHash = (await util.promisify(imageHash)({ ext: 'image/jpeg', data: imageBuffer }, 16, true)).toString()`

It actually works just fine, but I don't like getting the extraneous console output "No file extension found, attempting mime typing." I feel like it shouldn't output that, particularly since I passed in the ext.

**Comment by alexdpoon** [comment]
Not a rush, as I did find a workaround by adding a name with the .jpg extension.  I shouldn't need to do that, but it works.

`const myHash = (await util.promisify(imageHash)({ name: 'image.jpg', ext: 'image/jpeg', data: imageBuffer }, 16, true)).toString()`

**Comment by danm** [comment]
I've hidden this log by default now.
