### ISSUE TITLE
Errors trying to run inside Angular

### ISSUE THREAD

**Issue by grapevinegizmos** [danm/image-hash#31]
Somewhat mysterious series of error when running this in a Karma test:

The relevant line of the spec:  

      imageHash(`/assets/${assetFile}`, 16, true, (error, data) => {
            if (error) throw error
            hashString = data;
            console.log(data);
        })

27 03 2021 21:24:57.357:INFO [Chrome 89.0.489.90 (Mac OS 10.14.6)]: Connected on socket PXAwflpxridoCuiAAAA with id 0939149
27 03 2021 21:24:57.389:WARN [web-server]: 404: /_karma_webpack_/main.js
27 03 2021 21:24:57.413:WARN [web-server]: 404: /_karma_webpack_/main.js
Chrome 89.0.4389.90 (Mac OS 10.14.6): Executed 0 of 0 SUCCESS (0.001 secs / 0 secs)
TOTAL: 0 SUCCESS
TOTAL: 0 SUCCESS
✔ Browser application bundle generation complete.

Error: Module not found: Error: Can't resolve 'fs' in '/Users/jamer/Documents/VSCodeProjects/bkcopy/bkcopy/node_modules/image-hash/lib'

Error: Module not found: Error: Can't resolve 'fs' in '/Users/foo/Documents/VSCodeProjects/bkcopy/bkcopy/node_modules/request/lib'

Error: Module not found: Error: Can't resolve 'fs' in '/Users/foo/Documents/VSCodeProjects/bkcopy/bkcopy/node_modules/strtok3/lib'

Error: Module not found: Error: Can't resolve 'net' in '/Users/foo/Documents/VSCodeProjects/bkcopy/bkcopy/node_modules/forever-agent'

Error: Module not found: Error: Can't resolve 'net' in '/Users/foo/Documents/VSCodeProjects/bkcopy/bkcopy/node_modules/tough-cookie/lib'

Error: Module not found: Error: Can't resolve 'net' in '/Users/foo/Documents/VSCodeProjects/bkcopy/bkcopy/node_modules/tunnel-agent'

Error: Module not found: Error: Can't resolve 'tls' in '/Users/foo/Documents/VSCodeProjects/bkcopy/bkcopy/node_modules/forever-agent'

Error: Module not found: Error: Can't resolve 'tls' in '/Users/foo/Documents/VSCodeProjects/bkcopy/bkcopy/node_modules/tunnel-agent'

Version info:
Node: 12.14.1
OS: darwin x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cli                    11.2.6
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.5.5
typescript                      4.0.7
    
Joshs-MacBook-Pro:bkcopy joshkramer$ npm version
{
  bkcopy: '0.0.0',
  npm: '6.13.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '2.0.1',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.14.1',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.7.299.13-node.16',
  zlib: '1.2.11'
}
Joshs-MacBook-Pro:bkcopy joshkramer$ 

Thoughts on how to resolve?

**Comment by danm** [comment]
image-hash will only work with NodeJS and will not work in the browser. sorry.

**Comment by riyas-nextbrain** [comment]
@danm  is will detect duplicate image?
