### ISSUE TITLE
Upgrade to v5.0.2, Error: Unrecognized file extension, mime type or mismatch, ext: png / mime

### ISSUE THREAD

**Issue by munibrahman** [danm/image-hash#41]
Hi,

Thanks for keeping this library up to date, It's a breeze to use!

I upgraded from `4.0.1` to `5.0.2` and it throws an error every time I try to get a hash for a '.png' image.

The error is:
```
Error: Unrecognized file extension, mime type or mismatch, ext: png / mime
```

Rolling back to version 4.0.1 and trying the same file again doesn't cause any issues, so I strongly believe its something to do with the latter versions.

**Comment by c7nasr** [comment]
Error: SOI not found. That's a new issue. I'm downgrading hoping that resolve it

**Comment by danm** [comment]
Not sure why this would be, nothing jumps out to me in the code that would break png imports. I have updated the dependencies and the logs for better handling of errors. @munibrahman could you download the latest version `5.2.1` and hopefully that will have fixed the issue, or at least have better logs to diagnose it.
thanks
