### ISSUE TITLE
No support when the url doesn't end with jpg or png?

### ISSUE THREAD

**Issue by ghost** [danm/image-hash#7]
to reproduce:

imageHash('https://falabella.scene7.com/is/image/Falabella/prod11830022_6', 16, true, (error, data) => {
  if (error) throw error;
  console.log(data);
  // 0773063f063f36070e070a070f378e7f1f000fff0fff020103f00ffb0f810ff0
});

Error: Unrecognized file extension

**Comment by danm** [comment]
this should be fixed since the latest version
